# ------------------------------------------------------------------------------------ #
# BossEventManager Configuration                                                       #
# ------------------------------------------------------------------------------------ #

plugin-prefix: "&8[&bBossEvents&8] &r"
debug-mode: false

party:
  min-size: 2
  max-size: 5

economy:
  default-gem-cost: 100

bosses:
  skeleton_king:
    display-name: "&cSkeleton King"
    mythicmob-id: "SkeletonKingBoss"
    modelengine-id: "skeleking_model"
    gui-icon: "SKELETON_SKULL"
    description:
      - "&7A fearsome undead monarch."
      - "&7Known for his legion of minions."
      - ""
      - "&eDifficulty: &6Hard"
    gem-cost: 150
    required-level: 10
    arena-theme: "catacombs_theme" # Links to an ID in arena-themes
    rewards:
      - "eco give %player% 1000"
      - "minecraft:give %player% diamond 5"
      - "mm i give %player% SkeletonKingSword 1"
      - "broadcast &6%player% &eand their party have vanquished the &cSkeleton King&e!"
    party-size-scaling:
      health-per-member: 500.0
      damage-multiplier-per-member: 0.05

  goblin_chieftain:
    display-name: "&2Goblin Chieftain"
    mythicmob-id: "GoblinChieftainBoss"
    gui-icon: "PLAYER_HEAD"
    description:
      - "&7The brutish leader of the forest goblins."
      - "&7Watch out for his sneaky traps!"
      - ""
      - "&eDifficulty: &aEasy"
    gem-cost: 75
    arena-theme: "forest_outpost_theme" # Links to an ID in arena-themes
    rewards:
      - "eco give %player% 250"
      - "minecraft:give %player% iron_ingot 10"
      - "broadcast &6%player% &eand their party have bested the &2Goblin Chieftain&e!"

# GUI Settings
gui:
  boss-selection:
    title: "&1&lSelect a Boss Event"
    rows: 6
    items-per-page: 45
    no-bosses: "&cNo boss events are currently available."
  pagination:
    navigation-row: 6
    previous-page-col: 3
    page-info-col: 5
    next-page-col: 7
    previous-page-item:
      name: "&c<- Previous Page"
      material: "PAPER"
    next-page-item:
      name: "&aNext Page ->"
      material: "PAPER"
    page-info-item:
      material: "MAP"
      lore:
        - "&7Event Selection"
    filler-item:
      material: "BLACK_STAINED_GLASS_PANE"
  boss-item:
    name-format: "&6%boss_name%"
    lore-format:
      - "&7Cost: &e%gem_cost% Gems"
      - "&7Level: &b%required_level%"
      - ""
      - "%boss_description%"
      - ""
      - "&e&lClick to Challenge!"
  sounds:
    open: "BLOCK_CHEST_OPEN"
    close: "BLOCK_CHEST_CLOSE"
    nav-click: "UI_BUTTON_CLICK"
    nav-fail: "BLOCK_LEVER_CLICK"
    item-select: "ENTITY_EXPERIENCE_ORB_PICKUP"

# Arena Settings
arena-manager:
  # Name of the dedicated world where arenas will be pasted.
  # This world should ideally be a void world managed by a plugin like Multiverse-Core.
  arena-world-name: "world"
  # Starting coordinates for the first arena plot. Subsequent plots will be offset from this.
  start-x: 0
  start-y: 100 # Y-level for pasting schematics
  start-z: 0
  # Distance between arena plots to ensure separation.
  plot-separation-x: 1000
  plot-separation-z: 1000
  # Maximum concurrent arenas allowed. 0 for unlimited (within server reason).
  max-concurrent-arenas: 10

# Arena Themes / Schematics
# Each theme defines a schematic file and relative spawn points within that schematic.
# Schematics should be placed in the 'plugins/WorldEdit/schematics' or 'plugins/FastAsyncWorldEdit/schematics' folder.
arena-themes:
  catacombs_theme:
    display-name: "&8The Catacombs" # For potential future display in GUIs or messages
    schematic-file: "catacombs_arena.schem" # Filename (e.g., catacombs_arena.schem or boss_arenas/catacombs.schem)
    # Relative spawn points from the schematic's origin (paste point)
    # Format: "x,y,z" or "x,y,z,yaw,pitch"
    player-spawn-points: # List of potential spawn points for the party
      - "5,2,5,0,0"
      - "5,2,-5,0,0"
      - "-5,2,5,180,0"
      - "-5,2,-5,180,0"
    boss-spawn-point: "0,3,0,0,0" # Relative spawn point for the boss

  forest_outpost_theme:
    display-name: "&aForest Outpost"
    schematic-file: "forest_outpost.schem"
    player-spawn-points:
      - "3,1,7,0,0"
    boss-spawn-point: "0,1,0,0,0"

# Messages (Placeholder)
# messages:
#   no-permission: "%prefix%&cYou don't have permission."