# plugin.yml
name: events
version: ${project.version} # This will be replaced by Maven
main: io.mewb.bossEventManager.BossEventManagerPlugin
api-version: 1.19
author: MEWB - NOT INTENDED FOR RESALE, DO NOT SELL THIS PLUGIN, ONLY FOR PERSONAL USE
description: A custom boss event plugin with party integration and instanced arenas.


depend:
  - Vault
  - MythicMobs
  - FastAsyncWorldEdit

softdepend:
  - ModelEngine

commands:
  events: # Changed from bossevent
    description: Main command for the Event Manager.
    usage: /<command> <open|help|reload|admin> [args...] # Removed 'start' as it's GUI driven
    aliases: [event, ev] # New aliases
    permission: events.command.use

permissions:
  bosseventmanager.command.use:
    description: Allows usage of the main /events command (e.g. /events help).
    default: true
  bosseventmanager.command.open:
    description: Allows opening the event selection GUI via /events open.
    default: true
  .admin:
    description: Allows access to all admin commands for events.
    default: op
  bosseventmanager.admin.reload:
    description: Allows usage of the /events reload command.
    default: op
  bosseventmanager.admin.test:
    description: Allows usage of arena and party testing/debugging commands.
    default: op

